<div class="container">
    <div class="c-header">
        <h2>Widgets</h2>
    </div>

    <div id="c-grid" class="clearfix" data-columns="3">
        <div class="column size-1of3">
            <div class="card picture-list">
                <div class="card-header">
                    <h2>Augue laoreet rutrum
                        <small>Cras congue nec lorem eget posuere</small>
                    </h2>

                    <ul class="actions">
                        <li class="dropdown action-show">
                            <a href="" data-toggle="dropdown">
                                <i class="zmdi zmdi-more-vert"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <a href="">Refresh</a>
                                </li>
                                <li>
                                    <a href="">Manage Widgets</a>
                                </li>
                                <li>
                                    <a href="">Widgets Settings</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="pl-body clearfix">
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/1.png" alt="">
                        </a>
                    </div>

                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/2.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/3.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/4.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/5.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/6.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/7.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/8.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/9.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/1.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/2.png" alt="">
                        </a>
                    </div>
                    <div class="col-xs-3">
                        <a href="">
                            <img src="application/img/headers/square/3.png" alt="">
                        </a>
                    </div>
                </div>
            </div>
            <div class="card palette-Cyan bg">
                <ul class="actions a-alt">
                    <li class="dropdown">
                        <a href="" data-toggle="dropdown">
                            <i class="zmdi zmdi-more-vert"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-menu-right">
                            <li>
                                <a href="">Select City</a>
                            </li>
                            <li>
                                <a href="">Settings</a>
                            </li>
                        </ul>
                    </li>
                </ul>

                <div id="c-weather">
                    <div class="cw-current media">
                        <div class="pull-left cwc-icon cwci-30"></div>
                        <div class="cwc-info media-body">
                            <div class="cwci-temp">75°F</div>
                            <ul class="cwci-info">
                                <li>Austin, TX</li>
                                <li>Partly Cloudy</li>
                            </ul>
                        </div>
                    </div>
                    <div class="cw-upcoming">
                        <ul class="clearfix">
                            <li class="m-r-15"><i class="cwc-icon cwci-sm cwci-30"></i></li>
                            <li class="cwu-forecast">92/76</li>
                            <li>Partly Cloudy</li>
                        </ul>
                        <ul class="clearfix">
                            <li class="m-r-15"><i class="cwc-icon cwci-sm cwci-4"></i></li>
                            <li class="cwu-forecast">89/77</li>
                            <li>Thunderstorms</li>
                        </ul>
                        <ul class="clearfix">
                            <li class="m-r-15"><i class="cwc-icon cwci-sm cwci-4"></i></li>
                            <li class="cwu-forecast">88/76</li>
                            <li>Thunderstorms</li>
                        </ul>
                        <ul class="clearfix">
                            <li class="m-r-15"><i class="cwc-icon cwci-sm cwci-4"></i></li>
                            <li class="cwu-forecast">78/68</li>
                            <li>Thunderstorms</li>
                        </ul>
                        <ul class="clearfix">
                            <li class="m-r-15"><i class="cwc-icon cwci-sm cwci-47"></i></li>
                            <li class="cwu-forecast">78/65</li>
                            <li>Scattered Thunderstorms</li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header ch-alt">
                    <h2>Sample Form
                        <small>Pellentesque ac lectus sed elit dictum vehicula</small>
                    </h2>
                </div>

                <div class="card-body card-padding">
                    <div class="form-group fg-float m-b-30">
                        <div class="fg-line">
                            <input type="email" class="form-control input-sm">
                            <label class="fg-label">Name</label>
                        </div>
                    </div>

                    <div class="form-group fg-float m-b-30">
                        <div class="fg-line">
                            <input type="email" class="form-control input-sm">
                            <label class="fg-label">Email address</label>
                        </div>
                    </div>

                    <div class="form-group fg-float m-b-30">
                        <div class="fg-line">
                            <input type="email" class="form-control input-sm">
                            <label class="fg-label">Contact Number</label>
                        </div>
                    </div>

                    <div class="form-group fg-float">
                        <div class="fg-line">
                            <textarea class="form-control auto-size input-sm" data-autosize-on="true"
                                      style="overflow: hidden; word-wrap: break-word; height: 43px;"></textarea>
                            <label class="fg-label">Message</label>
                        </div>
                    </div>

                    <div class="clearfix"></div>

                    <div class="m-t-20">
                        <button class="btn btn-info waves-effect">Submit</button>
                        <button class="btn btn-link waves-effect">Cancel</button>
                    </div>
                </div>
            </div>
            <div class="card" id="calendar-widget">
                <div class="card-header cw-header palette-Teal-400 bg">
                    <div class="cwh-year">2016</div>
                    <div class="cwh-day">Friday, Sep 23</div>

                    <button class="btn palette-Light-Green bg btn-float waves-effect waves-circle waves-float"><i
                            class="zmdi zmdi-plus"></i></button>
                </div>

                <div class="card-body card-padding-sm">
                    <div id="cw-body" class="fc fc-ltr ui-widget">
                        <div class="fc-toolbar">
                            <div class="fc-left">
                                <button type="button"
                                        class="fc-prev-button ui-button ui-state-default ui-corner-left ui-corner-right">
                                    <span class="ui-icon ui-icon-circle-triangle-w"></span></button>
                            </div>
                            <div class="fc-right">
                                <button type="button"
                                        class="fc-next-button ui-button ui-state-default ui-corner-left ui-corner-right">
                                    <span class="ui-icon ui-icon-circle-triangle-e"></span></button>
                            </div>
                            <div class="fc-center"><h2>June 2014</h2></div>
                            <div class="fc-clear"></div>
                        </div>
                        <div class="fc-view-container" style="">
                            <div class="fc-view fc-month-view fc-basic-view">
                                <table>
                                    <thead class="fc-head">
                                    <tr>
                                        <td class="ui-widget-header">
                                            <div class="fc-row ui-widget-header">
                                                <table>
                                                    <thead>
                                                    <tr>
                                                        <th class="fc-day-header ui-widget-header fc-sun">Sun</th>
                                                        <th class="fc-day-header ui-widget-header fc-mon">Mon</th>
                                                        <th class="fc-day-header ui-widget-header fc-tue">Tue</th>
                                                        <th class="fc-day-header ui-widget-header fc-wed">Wed</th>
                                                        <th class="fc-day-header ui-widget-header fc-thu">Thu</th>
                                                        <th class="fc-day-header ui-widget-header fc-fri">Fri</th>
                                                        <th class="fc-day-header ui-widget-header fc-sat">Sat</th>
                                                    </tr>
                                                    </thead>
                                                </table>
                                            </div>
                                        </td>
                                    </tr>
                                    </thead>
                                    <tbody class="fc-body">
                                    <tr>
                                        <td class="ui-widget-content">
                                            <div class="fc-day-grid-container">
                                                <div class="fc-day-grid">
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-past"
                                                                        data-date="2014-06-01"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-past"
                                                                        data-date="2014-06-02"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-past"
                                                                        data-date="2014-06-03"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-past"
                                                                        data-date="2014-06-04"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-past"
                                                                        data-date="2014-06-05"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-past"
                                                                        data-date="2014-06-06"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-past"
                                                                        data-date="2014-06-07"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-past"
                                                                        data-date="2014-06-01">1
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-past"
                                                                        data-date="2014-06-02">2
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-past"
                                                                        data-date="2014-06-03">3
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-past"
                                                                        data-date="2014-06-04">4
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-past"
                                                                        data-date="2014-06-05">5
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-past"
                                                                        data-date="2014-06-06">6
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-past"
                                                                        data-date="2014-06-07">7
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-cyan fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">All Day</span>
                                                                            </div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-not-end bgm-orange fc-draggable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Long Event</span>
                                                                            </div>
                                                                        </a></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-past"
                                                                        data-date="2014-06-08"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-past"
                                                                        data-date="2014-06-09"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-past"
                                                                        data-date="2014-06-10"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-past"
                                                                        data-date="2014-06-11"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-past"
                                                                        data-date="2014-06-12"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-past"
                                                                        data-date="2014-06-13"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-past"
                                                                        data-date="2014-06-14"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-past"
                                                                        data-date="2014-06-08">8
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-past"
                                                                        data-date="2014-06-09">9
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-past"
                                                                        data-date="2014-06-10">10
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-past"
                                                                        data-date="2014-06-11">11
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-past"
                                                                        data-date="2014-06-12">12
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-past"
                                                                        data-date="2014-06-13">13
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-past"
                                                                        data-date="2014-06-14">14
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-event-container" colspan="2"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-not-start fc-end bgm-orange fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Long Event</span>
                                                                            </div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td rowspan="2"></td>
                                                                    <td rowspan="2"></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-cyan fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Lunch</span></div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td class="fc-event-container" rowspan="2"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-amber fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Birthday</span>
                                                                            </div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td rowspan="2"></td>
                                                                </tr>
                                                                <tr>
                                                                    <td></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-lightgreen fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Repeat</span></div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-green fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Meet</span></div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-past"
                                                                        data-date="2014-06-15"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-past"
                                                                        data-date="2014-06-16"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-past"
                                                                        data-date="2014-06-17"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-past"
                                                                        data-date="2014-06-18"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-past"
                                                                        data-date="2014-06-19"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-past"
                                                                        data-date="2014-06-20"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-past"
                                                                        data-date="2014-06-21"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-past"
                                                                        data-date="2014-06-15">15
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-past"
                                                                        data-date="2014-06-16">16
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-past"
                                                                        data-date="2014-06-17">17
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-past"
                                                                        data-date="2014-06-18">18
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-past"
                                                                        data-date="2014-06-19">19
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-past"
                                                                        data-date="2014-06-20">20
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-past"
                                                                        data-date="2014-06-21">21
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-lightblue fc-draggable fc-resizable">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Repeat</span></div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-past"
                                                                        data-date="2014-06-22"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-past"
                                                                        data-date="2014-06-23"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-past"
                                                                        data-date="2014-06-24"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-past"
                                                                        data-date="2014-06-25"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-past"
                                                                        data-date="2014-06-26"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-past"
                                                                        data-date="2014-06-27"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-past"
                                                                        data-date="2014-06-28"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-past"
                                                                        data-date="2014-06-22">22
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-past"
                                                                        data-date="2014-06-23">23
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-past"
                                                                        data-date="2014-06-24">24
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-past"
                                                                        data-date="2014-06-25">25
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-past"
                                                                        data-date="2014-06-26">26
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-past"
                                                                        data-date="2014-06-27">27
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-past"
                                                                        data-date="2014-06-28">28
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td class="fc-event-container"><a
                                                                            class="fc-day-grid-event fc-h-event fc-event fc-start fc-end bgm-amber fc-draggable fc-resizable"
                                                                            href="http://google.com/">
                                                                            <div class="fc-content"><span
                                                                                    class="fc-title">Google</span></div>
                                                                            <div
                                                                                class="fc-resizer fc-end-resizer"></div>
                                                                        </a></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-past"
                                                                        data-date="2014-06-29"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-past"
                                                                        data-date="2014-06-30"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-other-month fc-past"
                                                                        data-date="2014-07-01"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-other-month fc-past"
                                                                        data-date="2014-07-02"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-other-month fc-past"
                                                                        data-date="2014-07-03"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-other-month fc-past"
                                                                        data-date="2014-07-04"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-other-month fc-past"
                                                                        data-date="2014-07-05"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-past"
                                                                        data-date="2014-06-29">29
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-past"
                                                                        data-date="2014-06-30">30
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-other-month fc-past"
                                                                        data-date="2014-07-01">1
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-other-month fc-past"
                                                                        data-date="2014-07-02">2
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-other-month fc-past"
                                                                        data-date="2014-07-03">3
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-other-month fc-past"
                                                                        data-date="2014-07-04">4
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-other-month fc-past"
                                                                        data-date="2014-07-05">5
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                    <div class="fc-row fc-week ui-widget-content">
                                                        <div class="fc-bg">
                                                            <table>
                                                                <tbody>
                                                                <tr>
                                                                    <td class="fc-day ui-widget-content fc-sun fc-other-month fc-past"
                                                                        data-date="2014-07-06"></td>
                                                                    <td class="fc-day ui-widget-content fc-mon fc-other-month fc-past"
                                                                        data-date="2014-07-07"></td>
                                                                    <td class="fc-day ui-widget-content fc-tue fc-other-month fc-past"
                                                                        data-date="2014-07-08"></td>
                                                                    <td class="fc-day ui-widget-content fc-wed fc-other-month fc-past"
                                                                        data-date="2014-07-09"></td>
                                                                    <td class="fc-day ui-widget-content fc-thu fc-other-month fc-past"
                                                                        data-date="2014-07-10"></td>
                                                                    <td class="fc-day ui-widget-content fc-fri fc-other-month fc-past"
                                                                        data-date="2014-07-11"></td>
                                                                    <td class="fc-day ui-widget-content fc-sat fc-other-month fc-past"
                                                                        data-date="2014-07-12"></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                        <div class="fc-content-skeleton">
                                                            <table>
                                                                <thead>
                                                                <tr>
                                                                    <td class="fc-day-number fc-sun fc-other-month fc-past"
                                                                        data-date="2014-07-06">6
                                                                    </td>
                                                                    <td class="fc-day-number fc-mon fc-other-month fc-past"
                                                                        data-date="2014-07-07">7
                                                                    </td>
                                                                    <td class="fc-day-number fc-tue fc-other-month fc-past"
                                                                        data-date="2014-07-08">8
                                                                    </td>
                                                                    <td class="fc-day-number fc-wed fc-other-month fc-past"
                                                                        data-date="2014-07-09">9
                                                                    </td>
                                                                    <td class="fc-day-number fc-thu fc-other-month fc-past"
                                                                        data-date="2014-07-10">10
                                                                    </td>
                                                                    <td class="fc-day-number fc-fri fc-other-month fc-past"
                                                                        data-date="2014-07-11">11
                                                                    </td>
                                                                    <td class="fc-day-number fc-sat fc-other-month fc-past"
                                                                        data-date="2014-07-12">12
                                                                    </td>
                                                                </tr>
                                                                </thead>
                                                                <tbody>
                                                                <tr>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                    <td></td>
                                                                </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h2>Messages
                        <small>Praesent commodo cursus magnavel scelerisque nisl</small>
                    </h2>
                </div>

                <div class="card-body">
                    <div class="list-group lg-alt c-overflow mCustomScrollbar _mCS_4 mCS-autoHide mCS_no_scrollbar"
                         style="position: relative; overflow: visible;">
                        <div id="mCSB_4" class="mCustomScrollBox mCS-minimal-dark mCSB_vertical_horizontal mCSB_outside"
                             tabindex="0">
                            <div id="mCSB_4_container"
                                 class="mCSB_container mCS_y_hidden mCS_no_scrollbar_y mCS_x_hidden mCS_no_scrollbar_x"
                                 style="position: relative; top: 0px; left: 0px; width: 100%;" dir="ltr">
                                <a href="" class="list-group-item media">
                                    <div class="pull-left">
                                        <img class="avatar-img mCS_img_loaded" src="/img/profile-pics/1.jpg" alt="">
                                    </div>

                                    <div class="media-body">
                                        <div class="lgi-heading">David Villa Jacobs</div>
                                        <small class="lgi-text">Sorem ipsum dolor sit amet, consectetur adipiscing elit.
                                            Etiam mattis lobortis sapien non posuere
                                        </small>
                                    </div>
                                </a>

                                <a href="" class="list-group-item media">
                                    <div class="pull-left">
                                        <img class="avatar-img mCS_img_loaded" src="/img/profile-pics/5.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="lgi-heading">Candice Barnes</div>
                                        <small class="lgi-text">Quisque non tortor ultricies, posuere elit id, lacinia
                                            purus curabitur.
                                        </small>
                                    </div>
                                </a>

                                <a href="" class="list-group-item media">
                                    <div class="pull-left">
                                        <img class="avatar-img mCS_img_loaded" src="/img/profile-pics/3.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="lgi-heading">Jeannette Lawson</div>
                                        <small class="lgi-text">Donec congue tempus ligula, varius hendrerit mi
                                            hendrerit sit amet. Duis ac quam sit amet leo feugiat iaculis
                                        </small>
                                    </div>
                                </a>

                                <a href="" class="list-group-item media">
                                    <div class="pull-left">
                                        <img class="avatar-img mCS_img_loaded" src="/img/profile-pics/4.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="lgi-heading">Darla Mckinney</div>
                                        <small class="lgi-text">Duis tincidunt augue nec sem dignissim scelerisque.
                                            Vestibulum rhoncus sapien sed nulla aliquam lacinia
                                        </small>
                                    </div>
                                </a>

                                <a href="" class="list-group-item media">
                                    <div class="pull-left">
                                        <img class="avatar-img mCS_img_loaded" src="/img/profile-pics/2.jpg" alt="">
                                    </div>
                                    <div class="media-body">
                                        <div class="lgi-heading">Rudolph Perez</div>
                                        <small class="lgi-text">Phasellus a ullamcorper lectus, sit amet viverra quam.
                                            In luctus tortor vel nulla pharetra bibendum
                                        </small>
                                    </div>
                                </a>
                                <a href="" class="list-group-item view-more">
                                    <i class="zmdi zmdi-long-arrow-right"></i> View all
                                </a>
                            </div>
                        </div>
                        <div id="mCSB_4_scrollbar_vertical"
                             class="mCSB_scrollTools mCSB_4_scrollbar mCS-minimal-dark mCSB_scrollTools_vertical"
                             style="display: none;">
                            <div class="mCSB_draggerContainer">
                                <div id="mCSB_4_dragger_vertical" class="mCSB_dragger"
                                     style="position: absolute; min-height: 50px; height: 0px; top: 0px;"
                                     oncontextmenu="return false;">
                                    <div class="mCSB_dragger_bar" style="line-height: 50px;"></div>
                                </div>
                                <div class="mCSB_draggerRail"></div>
                            </div>
                        </div>
                        <div id="mCSB_4_scrollbar_horizontal"
                             class="mCSB_scrollTools mCSB_4_scrollbar mCS-minimal-dark mCSB_scrollTools_horizontal"
                             style="display: none;">
                            <div class="mCSB_draggerContainer">
                                <div id="mCSB_4_dragger_horizontal" class="mCSB_dragger"
                                     style="position: absolute; min-width: 50px; width: 0px; left: 0px;"
                                     oncontextmenu="return false;">
                                    <div class="mCSB_dragger_bar"></div>
                                </div>
                                <div class="mCSB_draggerRail"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card popular-post">
                <div class="card-header ch-img" style="background-image: url(img/headers/4.png); height: 150px;">
                    <h2>Recent Posts
                        <small>Venenatis Sollicitudin Ipsum</small>
                    </h2>

                    <button class="btn palette-Light-Green bg btn-float waves-effect waves-circle waves-float"><i
                            class="zmdi zmdi-plus"></i></button>
                </div>
                <div class="card-body m-t-20">
                    <div class="list-group lg-alt">
                        <a href="" class="list-group-item media">
                            <div class="pull-left">
                                <img class="avatar-img" src="/img/profile-pics/1.jpg" alt="">
                            </div>

                            <div class="media-body">
                                <div class="lgi-heading">David Villa Jacobs</div>
                                <small class="lgi-text">Sorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam
                                    mattis lobortis sapien non posuere
                                </small>
                            </div>
                        </a>

                        <a href="" class="list-group-item media">
                            <div class="pull-left">
                                <img class="avatar-img" src="/img/profile-pics/5.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Candice Barnes</div>
                                <small class="lgi-text">Quisque non tortor ultricies, posuere elit id, lacinia purus
                                    curabitur.
                                </small>
                            </div>
                        </a>

                        <a href="" class="list-group-item media">
                            <div class="pull-left">
                                <img class="avatar-img" src="/img/profile-pics/3.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Jeannette Lawson</div>
                                <small class="lgi-text">Donec congue tempus ligula, varius hendrerit mi hendrerit sit
                                    amet. Duis ac quam sit amet leo feugiat iaculis
                                </small>
                            </div>
                        </a>

                        <a href="" class="list-group-item media">
                            <div class="pull-left">
                                <img class="avatar-img" src="/img/profile-pics/4.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Darla Mckinney</div>
                                <small class="lgi-text">Duis tincidunt augue nec sem dignissim scelerisque. Vestibulum
                                    rhoncus sapien sed nulla aliquam lacinia
                                </small>
                            </div>
                        </a>

                        <a href="" class="list-group-item media">
                            <div class="pull-left">
                                <img class="avatar-img" src="/img/profile-pics/2.jpg" alt="">
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Rudolph Perez</div>
                                <small class="lgi-text">Phasellus a ullamcorper lectus, sit amet viverra quam. In luctus
                                    tortor vel nulla pharetra bibendum
                                </small>
                            </div>
                        </a>

                        <a href="" class="list-group-item view-more">
                            <i class="zmdi zmdi-long-arrow-right"></i> View all
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="column size-1of3">
            <div class="card">
                <div class="card-header">
                    <h2>Ongoing Tasks
                        <small>Maecenas seddiam eget risusvarius blandit</small>
                    </h2>
                </div>

                <div class="card-body">
                    <div class="list-group lg-alt">
                        <div class="list-group-item">
                            <div class="lgi-heading m-b-5">HTML5 Validation Report</div>

                            <div class="progress">
                                <div class="progress-bar" role="progressbar" aria-valuenow="95" aria-valuemin="0"
                                     aria-valuemax="100" style="width: 95%">
                                    <span class="sr-only">95% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="lgi-heading m-b-5">Google Chrome Extension</div>

                            <div class="progress">
                                <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (success)</span>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="lgi-heading m-b-5">Social Intranet Projects</div>

                            <div class="progress">
                                <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    <span class="sr-only">20% Complete</span>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="lgi-heading m-b-5">Bootstrap Admin Template</div>

                            <div class="progress">
                                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    <span class="sr-only">60% Complete (warning)</span>
                                </div>
                            </div>
                        </div>
                        <div class="list-group-item">
                            <div class="lgi-heading m-b-5">Youtube Client App</div>

                            <div class="progress">
                                <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
                                     aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                    <span class="sr-only">80% Complete (danger)</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <br>
                </div>
            </div>
            <div class="card">
                <div class="card-header ch-img" style="background-image: url(img/demo/note.png); height: 250px;"></div>
                <div class="card-header">
                    <h2>
                        Pellentesque Ligula Fringilla

                        <small>by Malinda Hollaway on 19th June 2015 at 09:10 AM</small>
                    </h2>
                </div>
                <div class="card-body card-padding">
                    <p>Donec ullamcorper nulla non metus auctor fringilla. Cras justo odio, dapibus ac facilisis in,
                        egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut
                        fermentum massa justo sit amet risus. Vestibulum id ligula porta felis euismod semper. Nulla
                        vitae elit libero, a pharetra </p>

                    <a href="" class="view-more"><i class="zmdi zmdi-long-arrow-right"></i> View Article...</a>
                </div>
            </div>
            <div class="card c-dark palette-Amber bg">
                <div class="card-header p-b-0">
                    <h2>For the past 30 days
                        <small>Tortor Magna Parturient</small>
                    </h2>
                    <ul class="actions a-alt">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown">
                                <i class="zmdi zmdi-more-vert"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <a href="">Change Date Range</a>
                                </li>
                                <li>
                                    <a href="">Change Graph Type</a>
                                </li>
                                <li>
                                    <a href="">Other Settings</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="card-body">
                    <div class="chart-edge">
                        <div class="ns-chart flot-chart" id="number-stats-chart"
                             style="padding: 0px; position: relative;">
                            <canvas class="flot-base"
                                    style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 439px; height: 200px;"
                                    width="439" height="200"></canvas>
                            <canvas class="flot-overlay"
                                    style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 439px; height: 200px;"
                                    width="439" height="200"></canvas>
                        </div>
                    </div>

                    <div class="list-group lg-alt lg-even-white">
                        <div class="list-group-item media">
                            <div class="pull-right hidden-sm">
                                <div class="sparkline-bar-1">
                                    <canvas width="88" height="40"
                                            style="display: inline-block; width: 88px; height: 40px; vertical-align: top;"></canvas>
                                </div>
                            </div>

                            <div class="media-body ns-item">
                                <small>Page Views</small>
                                <h3>47,896,536</h3>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-right hidden-sm">
                                <div class="sparkline-bar-2">
                                    <canvas width="88" height="40"
                                            style="display: inline-block; width: 88px; height: 40px; vertical-align: top;"></canvas>
                                </div>
                            </div>

                            <div class="media-body ns-item">
                                <small>Site Visitors</small>
                                <h3>24,456,799</h3>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-right hidden-sm">
                                <div class="sparkline-bar-3">
                                    <canvas width="88" height="40"
                                            style="display: inline-block; width: 88px; height: 40px; vertical-align: top;"></canvas>
                                </div>
                            </div>

                            <div class="media-body ns-item">
                                <small>Total Clicks</small>
                                <h3>13,965</h3>
                            </div>
                        </div>
                    </div>

                    <div class="p-5"></div>
                </div>
            </div>
            <div class="card rating-list">
                <div class="card-header text-center">
                    <h2>Average Rating 3.0</h2>
                    <div class="rl-star">
                        <i class="zmdi zmdi-star active"></i>
                        <i class="zmdi zmdi-star active"></i>
                        <i class="zmdi zmdi-star active"></i>
                        <i class="zmdi zmdi-star"></i>
                        <i class="zmdi zmdi-star"></i>
                    </div>
                </div>

                <div class="card-body">
                    <div class="list-group lg-alt">
                        <div class="list-group-item media">
                            <div class="pull-left">
                                1 <i class="zmdi zmdi-star"></i>
                            </div>

                            <div class="pull-right">20</div>

                            <div class="media-body">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="20"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                2 <i class="zmdi zmdi-star"></i>
                            </div>

                            <div class="pull-right">45</div>

                            <div class="media-body">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="45"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                3 <i class="zmdi zmdi-star"></i>
                            </div>

                            <div class="pull-right">60</div>

                            <div class="media-body">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                4 <i class="zmdi zmdi-star"></i>
                            </div>

                            <div class="pull-right">78</div>

                            <div class="media-body">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="78"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 78%">
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                5 <i class="zmdi zmdi-star"></i>
                            </div>

                            <div class="pull-right">22</div>

                            <div class="media-body">
                                <div class="progress">
                                    <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="22"
                                         aria-valuemin="0" aria-valuemax="100" style="width: 22%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card" id="todo-lists">
                <div class="card-header ch-dark palette-Purple-300 bg">
                    <h2>Todo lists
                        <small>Mattis Malesuada Risus</small>
                    </h2>

                    <ul class="actions a-alt">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown">
                                <i class="zmdi zmdi-more-vert"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <a href="">Change Date Range</a>
                                </li>
                                <li>
                                    <a href="">Change Graph Type</a>
                                </li>
                                <li>
                                    <a href="">Other Settings</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="card-body">
                    <div class="list-group lg-alt">
                        <div class="list-group-item-header palette-Purple text">Today</div>

                        <div class="list-group-item media checked">
                            <div class="pull-left">
                                <div class="avatar-char ac-check">
                                    <input class="acc-check" type="checkbox" checked="">

                                    <span class="acc-helper palette-Purple-300 bg">C</span>
                                </div>
                            </div>

                            <div class="media-body">
                                <div class="lgi-heading">Consectetur Sem Sollicitudin</div>
                                <small class="lgi-text">08:55 AM</small>
                            </div>
                        </div>

                        <div class="list-group-item media checked">
                            <div class="pull-left">
                                <div class="avatar-char ac-check">
                                    <input class="acc-check" type="checkbox" checked="">

                                    <span class="acc-helper palette-Purple-300 bg">E</span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Morbi leo risus, porta ac consectetur ac, vestibulum at eros.
                                </div>
                                <small class="lgi-text">07:32 AM</small>
                            </div>
                        </div>

                        <div class="list-group-item-header palette-Light-Blue text">Tomorrow</div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                <div class="avatar-char ac-check">
                                    <input class="acc-check" type="checkbox">

                                    <span class="acc-helper palette-Light-Blue bg">P</span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Porta Venenatis Quam</div>
                                <small class="lgi-text">10:30 P</small>
                            </div>
                        </div>

                        <div class="list-group-item media">
                            <div class="pull-left">
                                <div class="avatar-char ac-check">
                                    <input class="acc-check" type="checkbox">

                                    <span class="acc-helper palette-Light-Blue bg">N</span>
                                </div>
                            </div>
                            <div class="media-body">
                                <div class="lgi-heading">Nullam quis risus eget urna mollis ornare vel eu leo</div>
                                <small class="lgi-text">11:02 PM</small>
                            </div>
                        </div>

                        <a href="" class="list-group-item view-more">
                            <i class="zmdi zmdi-long-arrow-right"></i> View all
                        </a>
                    </div>

                    <button class="btn palette-Purple-300 bg btn-float waves-effect waves-circle waves-float"><i
                            class="zmdi zmdi-plus"></i></button>
                </div>
            </div>
        </div>
        <div class="column size-1of3">
            <div class="card">
                <div class="card-header ch-alt">
                    <h2>Contact Information
                        <small>Fusce eget dolor id justo luctus commodo vel pharetra nisi</small>
                    </h2>
                </div>
                <div class="card-body card-padding">
                    <div class="pmo-contact">
                        <ul>
                            <li class="ng-binding"><i class="zmdi zmdi-phone"></i> 00971123456789</li>
                            <li class="ng-binding"><i class="zmdi zmdi-email"></i> malinda.h@gmail.com</li>
                            <li class="ng-binding"><i class="zmdi zmdi-facebook-box"></i> malinda.hollaway</li>
                            <li class="ng-binding"><i class="zmdi zmdi-twitter"></i> @malinda (twitter.com/malinda)</li>
                            <li>
                                <i class="zmdi zmdi-pin"></i>
                                <address class="m-b-0 ng-binding">
                                    44-46 Morningside Road <br>
                                    Edinburgh <br>
                                    Scotland
                                </address>
                            </li>
                        </ul>
                    </div>

                    <a class="pmo-map" href="">
                        <img src="application/img/demo/map.png" alt="">
                    </a>
                </div>
            </div>
            <div class="card">
                <div class="card-header">
                    <h2>Praesent vitae justo purus
                        <small>In hendrerit lorem nislac lacinia</small>
                    </h2>
                </div>

                <div class="card-body">
                    <ul class="tab-nav tn-justified tn-icon" role="tablist">
                        <li role="presentation" class="active">
                            <a class="col-sx-4" href="#tab-1" aria-controls="tab-1" role="tab" data-toggle="tab">
                                <i class="zmdi zmdi-home icon-tab"></i>
                            </a>
                        </li>
                        <li role="presentation">
                            <a class="col-xs-4" href="#tab-2" aria-controls="tab-2" role="tab" data-toggle="tab">
                                <i class="zmdi zmdi-pin icon-tab"></i>
                            </a>
                        </li>
                        <li role="presentation">
                            <a class="col-xs-4" href="#tab-3" aria-controls="tab-3" role="tab" data-toggle="tab">
                                <i class="zmdi zmdi-star icon-tab"></i>
                            </a>
                        </li>
                    </ul>

                    <div class="tab-content p-20">
                        <div role="tabpanel" class="tab-pane animated fadeIn in active" id="tab-1">
                            <img src="application/img/headers/sm/6.png" class="img-responsive m-b-15 w-100" alt="">
                            Morbi id orci lacus. Nunc semper condimentum sem vel imperdiet. Praesent tristique purus id
                            est dictum, vel vestibulum ante interdum.
                        </div>

                        <div role="tabpanel" class="tab-pane animated fadeIn" id="tab-2">
                            <img src="application/img/headers/sm/2.png" class="img-responsive m-b-15 w-100" alt="">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet dapibus tellus.
                            Nullam aliquet dignissim semper. Cras sit amet ligula congue, dapibus enim id, dapibus
                            tellus.
                        </div>

                        <div role="tabpanel" class="tab-pane animated fadeIn" id="tab-3">
                            <img src="application/img/headers/sm/4.png" class="img-responsive m-b-15 w-100" alt="">
                            Serhoncus quis est sit amete in nisl molestie fringilla. Nunc vitae ante id magna feugiat
                            condimentum. Maecenas sit amet urna massa.
                        </div>
                    </div>
                </div>
            </div>
            <div class="card c-dark palette-Grey bg recent-signups">
                <div class="card-header p-b-0">
                    <h2>Most Recent Signups
                        <small>Magna Cursus Malesuada</small>
                    </h2>
                    <ul class="actions a-alt">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown">
                                <i class="zmdi zmdi-more-vert"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <a href="">Change Date Range</a>
                                </li>
                                <li>
                                    <a href="">Change Graph Type</a>
                                </li>
                                <li>
                                    <a href="">Other Settings</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="card-body">
                    <div class="sparkline-1 p-30">
                        <canvas style="display: inline-block; width: 361px; height: 50px; vertical-align: top;"
                                width="361" height="50"></canvas>
                    </div>

                    <ul class="rs-list">
                        <li>
                            <a href="">
                                <div class="avatar-char">B</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/5.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">L</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">A</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/4.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">Z</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">I</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">S</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">C</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">W</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/3.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">A</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/9.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">N</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">X</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">V</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/7.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/6.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <img class="avatar-img" src="/img/profile-pics/8.jpg" alt="">
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">F</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">E</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">A</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">A</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">M</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">O</div>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <div class="avatar-char">I</div>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="card c-dark profile-view palette-Blue bg">
                <div class="card-header text-center palette-Blue-400 bg">
                    <img src="/img/profile-pics/profile-pic.jpg" class="pv-img" alt="">
                    <h2 class="m-t-10">Malinda Hollway</h2>

                    <button class="btn palette-White bg btn-float waves-effect waves-circle waves-float">
                        <i class="palette-Blue text zmdi zmdi-email"></i>
                    </button>

                    <ul class="actions a-alt">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown">
                                <i class="zmdi zmdi-more-vert"></i>
                            </a>

                            <ul class="dropdown-menu dropdown-menu-right">
                                <li>
                                    <a href="">Edit</a>
                                </li>
                                <li>
                                    <a href="">Refresh</a>
                                </li>
                                <li>
                                    <a href="">View Profile</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>

                <div class="card-body p-30">
                    <div class="list-group lg-alt">
                        <div class="media">
                            <div class="pull-left">
                                <i class="pvb-icon zmdi zmdi-phone"></i>
                            </div>
                            <div class="media-body">
                                <div class="f-15">011 55694785</div>
                                <small>Home</small>
                            </div>
                        </div>

                        <div class="media">
                            <div class="pull-left">
                                <i class="pvb-icon zmdi zmdi-email"></i>
                            </div>
                            <div class="media-body">
                                <div class="f-15">m-hollaway@gmail.com</div>
                                <small>Email</small>
                            </div>
                        </div>

                        <div class="media">
                            <div class="pull-left">
                                <i class="pvb-icon zmdi zmdi-twitter"></i>
                            </div>
                            <div class="media-body">
                                <div class="f-15">@m-hollaway</div>
                                <small>Twitter</small>
                            </div>
                        </div>
                        <div class="media">
                            <div class="pull-left">
                                <i class="pvb-icon zmdi zmdi-github"></i>
                            </div>
                            <div class="media-body">
                                <div class="f-15">github.com/hollaway</div>
                                <small>Github</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card palette-Red-400 bg">
                <div class="pie-grid clearfix text-center">
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-2 easy-pie" data-percent="92">
                            <span class="ep-value">92</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Email<br> Scheduled</div>
                    </div>
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-3 easy-pie" data-percent="11">
                            <span class="ep-value">11</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Email<br> Bounced</div>
                    </div>
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-4 easy-pie" data-percent="52">
                            <span class="ep-value">52</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Email<br> Opened</div>
                    </div>
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-2 easy-pie" data-percent="44">
                            <span class="ep-value">44</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Storage<br>Remaining</div>
                    </div>
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-3 easy-pie" data-percent="78">
                            <span class="ep-value">78</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Web Page<br> Views</div>
                    </div>
                    <div class="col-xs-4 col-sm-6 col-md-4 pg-item">
                        <div class="easy-pie-4 easy-pie" data-percent="32">
                            <span class="ep-value">32</span>
                            <canvas height="75" width="75"></canvas>
                        </div>
                        <div class="pgi-title">Server<br> Processing</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
