<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>Partner <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Stadt Reutlingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Universitätsstadt Tübingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Gemeinde Kusterdingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>IHK Reutlingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Technologieparks Tübingen Reutlingen (TTR) GmbH</td>
                    <td></td>
                </tr>
                <tr>
                    <td>BioRegio STERN Management GmbH</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Verein zur Förderung der Biotechnologie und Medizintechnik e.V.</td>
                    <td></td>
                </tr>
                <tr>
                    <td>BIOPRO Baden-Württemberg GmbH</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Baden-Württemberg: Connected e.V</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Kompetenznetzwerk Medical Valley Hechingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Stuttgart Financial / VC-BW</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Forschungseinrichtungen <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>ZRM – Zentrum für Regenerationsbiologie und für Regenerative Medizin, Tübingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>NMI Naturwissenschaftliches und Medizinisches Institut an der Universität Tübingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Hochschule Reutlingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Eberhard Karls Universität Tübingen</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Schülerlabor Neurowissenschaften</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>
