#!/usr/bin/env php
<?php

use Simplicity\ReviewPlatform\Command\InitCommand;
use Zend\Console\Console;
use ZF\Console\Application;
use ZF\Console\Dispatcher;

require_once __DIR__ . '/vendor/autoload.php';

define('VERSION', '1.1.3');

$applicationConfiguration = require 'config/application.config.php';
$application = Zend\Mvc\Application::init($applicationConfiguration);

$dispatcher = new Dispatcher($application->getServiceManager());
$dispatcher->map('init', new InitCommand());

$application = new Application(
    'Builder',
    VERSION,
    include __DIR__ . '/config/routes.php',
    Console::getInstance(),
    $dispatcher
);

$exit = $application->run();
exit($exit);