<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>XING</h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>
