<div class="container">
    <div class="c-header">
        <h2>Vernetzungen / Gruppen</h2>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Kunden <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Partner <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Vertrieb <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Mitarbeiter <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>
