<div class="container">

    <div class="card">
        <div class="card-header clearfix">
            <h2 class="pull-left">Eigene Cluster
                <small>Versorgen sie bestimmte Gruppen mit Inhalten indem sie Bereiche anlegen und einladen</small>
            </h2>
            <button class="btn btn-success btn-icon-text waves-effect pull-right bg"><i class="zmdi zmdi-plus"></i>
                Vernetzung erstellen
            </button>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Updates</th>
                    <th></th>
                    <th>Aktionen</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="/networking/show/1">Mitarbeiter</a></td>
                    <td>4 neue Kommentare</td>
                    <td>https://github.com/humhub/humhub</td>
                    <td><a href="/networking/edit/1">bearbeiten</a></td>
                </tr>
                <tr>
                    <td>Partner</td>
                    <td></td>
                    <td>https://github.com/humhub/humhub</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Kunden</td>
                    <td></td>
                    <td>https://sonata-project.org/get-started</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Öffentlich</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Gruppen</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Empfohlene Cluster
                <small>Diese Cluster können wir ihnen auf Grund ihrer Ziele empfehlen</small>
            </h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Teilnehmer</th>
                    <th>Status</th>
                    <th>Aktionen</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Kunden</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Mitarbeiter</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>


    <div class="card">
        <div class="card-header">
            <h2>Cluster suchen
                <small>Durchsuchen sie alle Cluster von United People</small>
            </h2>
        </div>
    </div>

    <div class="card">
        <div class="card-header clearfix">
            <h2 class="pull-left">
                Premium-Cluster
                <small>Exclusive Cluster</small>
            </h2>
            <button class="btn btn-success btn-icon-text waves-effect pull-right bg"><i class="zmdi zmdi-plus"></i>
                Premium-Cluster beitreten
            </button>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Teilnehmer</th>
                    <th>Status</th>
                    <th>Aktionen</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Kunden</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Mitarbeiter</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
