<div class="container">
    <div class="c-header">
        <h2>Regional vernetzt, global erfolgreich<small>Vernetzungen für mehr Innovation und Wettbewerbsfähigkeit</small></h2>
    </div>

    <div class="card">
        <div class="card-body card-padding">
            Experten sind sich einig: Netzwerken ist ein entscheidendes
            Kriterium für den Unternehmenserfolg. Das gilt insbesondere für
            mittlere und kleinere Firmen. Aus diesem Grund bietet die IHK über
            35 verschiedene Berufs-, Fach- und Branchen-Netzwerke an. Hier
            treffen sich Verantwortliche aus unterschiedlichen Unternehmen
            der Region. Die Netzwerke sind eine zeit- und kostengünstige Form
            der Weiterbildung für Chefs, Mitarbeiter und Führungskräfte und
            bieten die Möglichkeit zum persönlichen Austausch untereinander.
            <h3>Mehr Wissen</h3>
            Wer über den eigenen Tellerrand hinausschaut, kommt weiter.
            Die IHK-Netzwerke bieten Fachvorträge zu aktuellen Themen,
            vermitteln Praxis-Tipps für den Berufsalltag und präsentieren
            Best-Practice-Beispiele aus anderen Unternehmen. Was in den
            Netzwerken läuft, bestimmen die Mitglieder selbst: Themenwünsche
            oder Referentenempfehlungen sind herzlich willkommen.
            Die IHK übernimmt die Organisation.
            <h3>Mehr Kontakte</h3>
            Auch in Zeiten von Twitter, Facebook und Co. zählt der direkte
            Kontakt: Vorträge, Diskussionen und Networking von und mit
            Menschen, denen man in die Augen blicken kann, sind einfach
            entspannter und nachhaltiger als der virtuelle Austausch. Alle Treffen
            klingen mit einem lockeren Come-together aus. Hier kann man
            Kontakte knüpfen und neue Geschäftsbeziehungen aufbauen.
            <h3>Mehr Erfolg</h3>
            Wer sich mit den Strategien und Problemen anderer befasst, kann
            folgenschwere Fehler vermeiden. Der regelmäßige Austausch im
            Netzwerk trägt so zum Erfolg des eigenen Unternehmens bei.
            Machen Sie sich Ihr eigenes Bild und entscheiden Sie sich für die
            Teilnahme in einem IHK-Netzwerk.
        </div>
    </div>


</div>
