<div class="container">
    <div class="c-header" style="padding: 0 28px">
        <h2>Neues Ziel definieren
            <small>Ziele müssen
                <abbr title="Ziele müssen eindeutig definiert sein (nicht vage, sondern so präzise wie möglich)">spezifisch</abbr>,
                <abbr title="Ziele müssen messbar sein (Messbarkeitskriterien)">messbar</abbr> und
                <abbr title="Ziele müssen möglich sein">realisitisch</abbr> sein.
                Sie sollten <abbr
                    title="zu jedem Ziel gehört eine klare Terminvorgabe, bis wann das Ziel erreicht sein muss">terminiert</abbr>
                und vom Bearbeiter <abbr
                    title="Ziele müssen von den Empfängern akzeptiert werden/sein">akzeptiert</abbr> werden
            </small>
        </h2>
    </div>

    <div class="card">
        <div class="card-body card-padding">
            <div class="form-group">
                <div class="fg-line">
                    <input type="text" class="form-control input-lg" placeholder="Zusammenfassung des Ziels">
                </div>
            </div>
            <div class="row">
                <div class="input-group form-group">
                    <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span>
                    <div class="dtp-container fg-line">
                        <input type="text" class="form-control date-picker" placeholder="Click here...">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="fg-line">
                            <input type="text" class="form-control" placeholder="Messkriterium">
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="fg-line">
                            <input type="text" class="form-control" placeholder="Aktueller Wert">
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <div class="fg-line">
                            <input type="text" class="form-control" placeholder="Erwarteter Wert">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <button type="submit" class="btn btn-primary waves-effect pull-right">Speichern</button>
            </div>
        </div>
    </div>
</div>
