<div class="container">
    <div class="c-header" style="padding: 0 28px;">
        <h3 style="color: #fff;">
            Entwicklung einer Strategie
            <a href="<?php echo $this->url('strategies', ['action' => 'create']); ?>" type="submit" class="btn btn-default btn-lg waves-effect pull-right">Strategie anwenden</a>
        </h3>
    </div>

    <div class="card">
        <div class="card-body card-padding">

            <div class="panel-group" role="tablist" aria-multiselectable="true">
                <div class="panel panel-collapse">
                    <div class="panel-heading active" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Harvard-Konzept
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne">
                        <div class="panel-body">
                            1. Identifikation des „Strategischen Profils“
                            2. Analyse relevanter Umweltausschnitte
                            3. Strategische Prognosen
                            4. Analyse der Unternehmensstärke und -schwäche
                            5. Ressourcenanalyse
                            6. Entwicklung der strategischen Handlungsalternativen
                            7. Konsistenztest
                            8. Strategische Wahl
                        </div>
                    </div>
                </div>
                <div class="panel panel-collapse">
                    <div class="panel-heading" role="tab" id="headingTwo">
                        <h4 class="panel-title">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                Fünf Phasen Modell
                            </a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo">
                        <div class="panel-body">
                            Phase: Analyse der gegenwärtigen Situation und der Aussicht
                            Phase: Strategieformulierung
                            Phase: Erstellung der strategischen Planung und der Politik
                            Phase: Umbau der Organisation nach der Strategien
                            Phase: Umsetzung der Strategien
                        </div>
                    </div>
                </div>
                <div class="panel panel-collapse">
                    <div class="panel-heading" role="tab" id="headingThree">
                        <h4 class="panel-title">
                            <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                Ressourcenbasierter Strategieansatz
                            </a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="collapse" role="tabpanel" aria-labelledby="headingThree">
                        <div class="panel-body"></div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Kontinuierlicher Verbesserungsprozess
                <small>Eine Denkweise, die mit stetigen Verbesserungen in kleinen Schritten die Wettbewerbsfähigkeit der Unternehmen stärken will. KVP bezieht sich auf die Produkt-, die Prozess- und die Servicequalität.
                </small>
            </h2>
        </div>
        <div class="card-body card-padding">
            Arbeitssystem festlegen und abgrenzen (Was soll verbessert werden?)
            Ist-Zustand und Soll-Zustand anhand von Kennzahlen beschreiben
            Probleme beschreiben und bewerten (Häufigkeit pro Zeiteinheit oder Objekteinheit – Angebot, Auftrag, Los etc.)
            Probleme bewerten (Zeit, Geld, Energie, Stress pro Zeiteinheit)
            Problemanalyse (Ursachen, Zusammenhänge, Schnittstellen, Nebenwirkungen)
            Lösungsideen sammeln (z. B. Brainstorming)
            Lösungsideen bewerten und entscheiden
            Maßnahmen ableiten, Aufwand und Ertrag bewerten
            Ergebnispräsentation vor dem Entscheidungsgremium
            Maßnahmen vereinbaren (Wer tut was bis wann?) und Ressourcen klären
            Maßnahmen umsetzen
            Erfolg prüfen
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Hightech-Strategie
                <small>Mit Hilfe der neuen Hightech-Strategie soll Deutschland zum weltweiten Innovationsführer
                    werden.
                </small>
            </h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Schwerpunkt</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Industrie 4.0</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Smart Services</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Cloud Computing</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Digitale Vernetzung</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Digitale Wissenschaft</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Digitale Bildung</td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                <tr>
                    <td>Digitale Lebenswelten
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

</div>
