<div class="container">
    <div class="c-header">
        <h2>Portale</h2>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Am Standort Reutlingen</h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Dr. Christoph-M. Pfefferle, Geschäftsführer</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Markus Flammer, Prokurist</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Monika Lipp, Rechnungs- und Finanzwesen</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Am Standort Tübingen</h2>
        </div>

        <div class="card-body table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>Wolfgang Kleinmann, Geschäftsführer</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Christine Decker, Projektleiterin</td>
                    <td></td>
                </tr>
                <tr>
                    <td>Angela Lill, Vermietungen</td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>


</div>
