<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>Sixt <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body">
            Sixt @ kununu

            https://www.linkedin.com/in/johanna-scheffer-48971323
            johanna.scheffer@sixt.com

            SIXT
            Mitarbeiter	5.120
            Umsatz		1,939 Mrd. € (2015)[1]

            DIAGRAMM

            SIXT
            Mit der Sixt Autovermietung, dem Premium-Carsharing-Anbieter DriveNow, der umfangreichen Leistungspalette für Firmen- und Privatkunden der Sixt Leasing AG und dem Transferdienst myDriver bietet Sixt eine Palette von ineinandergreifenden Mobilitätsangeboten, wie sie kein anderer Autovermieter sonst vorweisen kann. (http://www.deraktionaer.de/aktie/real-depot-wert-sixt---rekordfahrt-geht-weiter--allzeithoch-in-sichtweite---turbo-call-weiter-ueber-400--im-plus-266260.htm)

            - http://www.wallstreet-online.de/aktien/sixt-aktie
            - http://www.wallstreet-online.de/aktien/sixt-vz-aktie
            - http://www.deraktionaer.de/aktien/DE0007231326.htm?dId=DE0007231326&app=510-242

        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h2>Avis <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body ">
            AVIS
            - http://www.wallstreet-online.de/anleihen/a1zymt-avis-budget-car-rent-llc-avis-budget-finance-inc-anleihe-5-25-bis-15-03-2025


        </div>
    </div>

</div>
