<div class="container">

    <div class="card">
        <div class="card-header">
            <h2>Videos <small>Basic example without any additional modification classes</small></h2>
        </div>

        <div class="card-body table-responsive">

            Aktien im Kopf
            https://www.youtube.com/channel/UCpV9LpCg4uwYCQZ3qoEn_YQ

            Unternehmenskanal
            https://www.youtube.com/channel/UCnYhrUdZTBRe2s1pu-mF2mg

            Dirk Kräuter
            https://www.youtube.com/channel/UCst-bv-rrm31AU27gNZ88qQ

            Alex Fischer
            https://www.youtube.com/user/ImmoProfiNRW

            Punk
            https://www.youtube.com/user/investmentpunkacadem

        </div>
    </div>

</div>
